#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

if (is_readable(__DIR__ . '/config/dev/env.php')) {
    $config = require __DIR__ . '/config/dev/env.php';
} else {
    $config = require __DIR__ . '/config/env/dev.php';
}

$dependencies = require __DIR__ . '/app/dependencies.php';

$app = new \App\CliApp($config, $dependencies);
addTasks($app);

$app->run();

function addTasks(\Symfony\Component\Console\Application $app){
    $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator(__DIR__ .'/app/Commands',
        FilesystemIterator::SKIP_DOTS | FilesystemIterator::CURRENT_AS_SELF));
    foreach ($iterator as $file){
        if ($file->getSubPathName() !== 'AbstractCommand.php'){
            $className = substr($file->getPath(), strlen(__DIR__ . 'app/Commands/'));
            $className = 'App\\Commands' . str_replace('/', '\\', $className) . '\\' . substr($file->getFilename(), 0, -strlen($file->getExtension()) - 1);

            $command = new $className();
            if ($command instanceof \Symfony\Component\Console\Command\Command) {
                $app->add($command);
            }
        }
    }

}
