parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  Illuminate\Database\Connection:
    factory: [ 'App\Model\ConnectionFactory','build' ]
    arguments:
      $host: '%env(DB_HOST)%'
      $database: '%env(DB_DATABASE)%'
      $user: '%env(DB_USER)%'
      $password: '%env(DB_PASSWORD)%'
      $driver: '%env(DB_DRIVER)%'
      $port: '%env(DB_PORT)%'
